### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by Ramishscrapper**
- I improve the style fix the link title position now it don't move up and down it stick to it's position.
- I fix the js error which is getImageData() error The canvas
- Add and link image from repo not from the live url

### CODE REVIEW

**Comment by ziadevcom** [comment]
hey, i appreciate the time you spent on the changes.

but i coded this like more than year ago, i dont see anything malicious in the code but i want to make sure if you tested the app on your end.

**Comment by Ramishscrapper** [comment]
@ziadevcom You can also see what I changes did, Yes I test on my side it is perfectly as your live github page you can check the issue created by someone he also face the issue I fix that js issue.

**Comment by ziadevcom** [comment]
i was about to merge it why did you close it?

**Comment by Ramishscrapper** [comment]
No, I think the error that I fix it some it times shows sometimes not so I thought why should I add up anything if it is already working.
Thanks for the response.

**Comment by ziadevcom** [comment]
understandable, have a nice day.

**Comment by Ramishscrapper** [comment]
@ziadevcom bro can I talk with you personally on dm?

**Comment by ziadevcom** [comment]
yeah sure

**Comment by Ramishscrapper** [comment]
@ziadevcom Great, do you have Instagram account ? so we can talk there!

**Comment by ziadevcom** [comment]
add me on discord: Zia#5550

**Comment by Ramishscrapper** [comment]
@Ramishscrapper Ramish Hassan Riaz#9256 
this is mine username sorry I am not familiar with discord so not exactly know to add you on discord

**Pull request closed without merging**
